spring.application.name=Backend
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3308/new_vehicle_composant?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=admin0023
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host =smtp.gmail.com
spring.mail.port =587
spring.mail.username=ilyaachi03@gmail.com
spring.mail.password=dslitkcqskfxjglq
spring.mail.properties.mail.smtp.auth =true
spring.mail.properties.mail.smtp.starttls.enable =true
app.frontend.url =  http://localhost:5173/